"""
This module serves as an isolated client for interacting with the Google Gemini API.
It handles prompt transmission and response retrieval while managing errors and
configuration internally, ensuring the rest of the backend remains decoupled from
specific LLM implementation details.
"""

import os
import json
import requests
from typing import Optional

# Configuration
_API_URL = "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent"
_TIMEOUT_SECONDS = 30
_FALLBACK_MESSAGE = "The system is temporarily unavailable."

def generate_response(prompt: str) -> str:
    """
    Sends a prompt to the Gemini API and returns the generated text.

    Args:
        prompt (str): The fully constructed natural language prompt.

    Returns:
        str: The text generated by the LLM, or a fallback message on failure.
    """
    api_key = os.environ.get("GEMINI_API_KEY")
    
    if not api_key:
        # Log logic would go here usually, but restricted by constraints.
        return _FALLBACK_MESSAGE

    headers = {
        "Content-Type": "application/json"
    }
    
    # Using the query parameter for the key is standard for this endpoint
    params = {
        "key": api_key
    }

    payload = {
        "contents": [{
            "parts": [{"text": prompt}]
        }]
    }

    try:
        response = requests.post(
            _API_URL,
            headers=headers,
            params=params,
            json=payload,
            timeout=_TIMEOUT_SECONDS
        )
        
        response.raise_for_status()
        
        data = response.json()
        
        # Parse the nested response structure
        # Expected: {"candidates": [{"content": {"parts": [{"text": "..."}]}}]}
        candidates = data.get("candidates")
        if not candidates:
            return _FALLBACK_MESSAGE
            
        content = candidates[0].get("content")
        if not content:
            return _FALLBACK_MESSAGE
            
        parts = content.get("parts")
        if not parts:
            return _FALLBACK_MESSAGE
            
        text = parts[0].get("text")
        if not text:
            return _FALLBACK_MESSAGE

        return text

    except requests.exceptions.RequestException:
        return _FALLBACK_MESSAGE
    except (ValueError, KeyError, IndexError):
        # Catch JSON parsing errors or unexpected structure
        return _FALLBACK_MESSAGE
    except Exception:
        # Catch-all to ensure no uncaught exceptions per requirements
        return _FALLBACK_MESSAGE
