"""
This module serves as an isolated client for interacting with the Google Gemini API.
It handles prompt transmission and response retrieval while managing errors and
configuration internally, ensuring the rest of the backend remains decoupled from
specific LLM implementation details.
"""

import os
import logging

import google.generativeai as genai

logger = logging.getLogger(__name__)

# Configuration
_MODEL_NAME = "gemini-flash-latest"
_FALLBACK_MESSAGE = "The system is temporarily unavailable."

# Module-level flag to track SDK configuration
_sdk_configured = False


def _configure_sdk() -> None:
    """Configure the Gemini SDK with the API key (once per process)."""
    global _sdk_configured
    if _sdk_configured:
        return

    api_key = os.environ.get("GEMINI_API_KEY")

    if not api_key:
        logger.error("GEMINI_API_KEY is not set in environment")
        raise RuntimeError("GEMINI_API_KEY is not set. Please add it to your .env file.")

    if "your" in api_key.lower() and "key" in api_key.lower():
        logger.error("GEMINI_API_KEY contains placeholder value: %s", api_key)
        raise RuntimeError(
            f"GEMINI_API_KEY contains a placeholder value '{api_key}'. "
            "Please replace it with your actual API key in .env"
        )

    genai.configure(api_key=api_key)
    _sdk_configured = True
    logger.debug("Gemini SDK configured successfully")


def generate_response(prompt: str) -> str:
    """
    Sends a prompt to the Gemini API and returns the generated text.

    Args:
        prompt (str): The fully constructed natural language prompt.

    Returns:
        str: The text generated by the LLM, or a fallback message on failure.
    """
    try:
        _configure_sdk()

        model = genai.GenerativeModel(_MODEL_NAME)
        response = model.generate_content(prompt)

        if not response.text:
            logger.debug("Gemini response has no text content")
            return _FALLBACK_MESSAGE

        return response.text

    except RuntimeError:
        # Re-raise configuration errors (missing/invalid API key)
        raise
    except Exception as e:
        logger.error("Gemini API request failed: %s", e)
        return _FALLBACK_MESSAGE
